/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Actorcard: typeof import('./src/components/actorcard.vue')['default']
    Actordetail: typeof import('./src/components/actordetail.vue')['default']
    Article: typeof import('./src/components/article.vue')['default']
    Cinemashowtime: typeof import('./src/components/cinemashowtime.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loginmodal: typeof import('./src/components/loginmodal.vue')['default']
    Moviecard: typeof import('./src/components/moviecard.vue')['default']
    Moviedetail: typeof import('./src/components/moviedetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signupmodal: typeof import('./src/components/signupmodal.vue')['default']
    Ticketbookingmodal: typeof import('./src/components/ticketbookingmodal.vue')['default']
  }
}
